### ISSUE TITLE
Rework constitutive law type

### ISSUE THREAD

**Issue by Maarrk** [Shimul-Baidya/MBDyn#5]
The `ConstitutiveLaw` class has an abstract method `name`. Then every subclass defines `law_type` and implements this method as just `return self.law_type` every time.

Can we move `law_type` to `ConstitutiveLaw` and remove `name()` altogether?

**Comment by Shimul-Baidya** [comment]
I did as you said: [Relevant commit](https://github.com/Shimul-Baidya/MBDyn/commit/0c8aa989447e344cd1dff76cce27b161ebc84355)

**Comment by Maarrk** [comment]
Looks good, now I can clearly see what's shared and what's specific to given laws
