### ISSUE TITLE
Error Handling in Initialization for LinearViscoelasticGeneric: Need for Manual init Method

### ISSUE THREAD

**Issue by Shimul-Baidya** [Shimul-Baidya/MBDyn#9]
As we are skipping manually writing the __init__ method, there are some Errors that are not being raised during the initialization of the entities, the errors are being raised when the __str__ method is called only.

For example, in the LinearViscoelasticGeneric class, either `viscosity` or `factor` should be provided. If both are provided, then a `ValueError` should be raised. But here, LinearViscoelasticGeneric constitutive law can be initialized with both `viscosity` and `factor` provided, without getting any error. The error will show up only when the __str__ method is called.

https://github.com/Shimul-Baidya/MBDyn/blob/83b5bade96c2aaa1026b19bd7d5d39e98064fffe/contrib/PythonPreprocessor/MBDynLib.py#L4110-L4130

Is it okay, or should I manually write the __init__ method for this types of scenario?

**Comment by zanoni-mbdyn** [comment]
It seems to me that this is case in which you might want to consider adding a custom [validator](https://docs.pydantic.dev/latest/concepts/validators/). You could attach one validator for each field, checking that the other has not been set before, or - maybe better - you could use a model validator to check if they were both set.

**Comment by Shimul-Baidya** [comment]
Okay, I used model_validator.

https://github.com/Shimul-Baidya/MBDyn/blob/058d9601bbbbf25e65e9b93a057d030f4acf2500/contrib/PythonPreprocessor/MBDynLib.py#L4153-L4180
